### ISSUE TITLE
Running this on a server?

### ISSUE THREAD

**Issue by FreshDonut** [alastairparagas/nikeshoes-bot#1]
This is cool Alastair! Quick question. How would one run this on a server such as heroku or parse's cloud code?

**Comment by alastairparagas** [comment]
Hello @byooo! This code runs straight on a NodeJS platform. I have never done a full Parse deploy, so I would not know.

**Comment by neilamin** [comment]
how hard would it be to alter this for adidas if I am still a first-year CS student with no JS experience?

**Comment by alastairparagas** [comment]
No further comments, closing
